Update log-atrest

diff --git a/log/usr.local.bin/log-atrest b/log/usr.local.bin/log-atrest
--- a/log/usr.local.bin/log-atrest
+++ b/log/usr.local.bin/log-atrest
@@ -28,7 +28,7 @@
 
 source log.defs
 
-LOGFILENAME=$( ${DATE} '+Ymd' )
+LOG_FILENAME=$( ${DATE} '+Ymd' )
 
 while  [ "${1}" != "" ] ; do
   case ${1} in
@@ -37,24 +37,24 @@ while  [ "${1}" != "" ] ; do
       exit 0
       ;;
     -v)
-      VERBOSE=1
+      OPTION_VERBOSE=1
       ;;
     *)
-      LOGFILENAME=${1}
-      ;;
+      LOG_FILENAME=${1}
+      ;;_
   esac
   shift
 done
 
-if [ ! -f "${LOGDIR}${LOGFILENAME}" ] ;  then echo "log-atrest: bad or missing log file" ; exit 9 ; fi
+if [ ! -f "${LOGDIR}${LOG_FILENAME}" ] ;  then echo "log-atrest: bad or missing log file" ; exit 9 ; fi
 
-POSITIONS="$(${LOGPOSITIONS} ${LOGFILENAME})"
-POSITIONCOUNT=$(${GREP} -c '^' <<< "${POSITIONS}")
+POSITIONS="$(${LOGPOSITIONS} ${LOG_FILENAME})"
+POSITIONCOUNT=$(${GREP} -c '^' <<_< "${POSITIONS}")
 
 if [ ${POSITIONCOUNT} -eq 1 ] ; then
-  if [ ${VERBOSE} ] ; then echo "yes" ; fi
+  if [ ${OPTION_VERBOSE} ] ; then echo "yes" ; fi
   exit 0
 else
-  if [ ${VERBOSE} ] ; then echo "no" ; fi
+  if [ ${OPTION_VERBOSE} ] ; then echo "no" ; fi
   exit 1
 fi
