Tweaking

diff --git a/log/usr.local.bin/log-stops b/log/usr.local.bin/log-stops
--- a/log/usr.local.bin/log-stops
+++ b/log/usr.local.bin/log-stops
@@ -41,11 +41,16 @@ OPT_ALLSTOPS=
 FILESPECS=
 RESTRICT=
 SIMPLE=
+SELECTOR="Main engine STATE"
 
 while [ "${1}" != "" ] ; do
   case ${1} in
     -a) # Return all stops
       OPT_ALLSTOPS="yes"
+      ;;
+    -e) # Set engine label selector
+      shift
+      SELECTOR=${1}
       ;;
     -f) # Return first stop only
       RESTRICT="first"
@@ -74,16 +79,20 @@ if [ "${FILESPECS}" == "" ] ; then
   echo "usage: log-stops -h"
   exit 1
 fi
+
+if [ "${SELECTOR}" == "" ] ; then
+  echo "log-stops: bad or missing selector for -e"
+  exit 1
+fi
     
 ALLSTOPS=
 for FILENAME in ${FILESPECS} ; do
   POSITIONS=$(${LOGPOSITIONS} $(${BASENAME} ${FILENAME}))
   POSITIONCOUNT=$(${GREP} -c '^' <<< "${POSITIONS}")
   STARTPOS=$( ${HEAD} -1 <<<${POSITIONS} )
-  STOPS=$(${GREP} -h 'POSITION\|ENGINE' ${FILENAME} \
-    | ${GREP} -B1 'ENGINE' \
-    | ${GREP} '{' \
-    | ${AWK} '{ print $5,$6,$7,$8,$9",","\"date\":","\""$1"\"",$10 }')
+  STOPS=$(${GREP} -h "POSITION\|${SELECTOR}" ${FILENAME} | ${GREP} -B1 'STATE' | ${GREP} 'POSITION' |\
+  ${AWK} "{}"
+  
   STOPCOUNT=$(${GREP} -c '^' <<< "${STOPS}")
 
   if [ ${POSITIONCOUNT} -gt 1 ] ; then
