Revise install strategy

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,14 +1,14 @@
 #!/bin/bash
 
-LOG_FOLDER=log/
-WORDPRESS_FOLDER=wordpress/
+LOG_SOURCE_DIRECTORY=log/
+WORDPRESS_SOURCE_DIRECTORY=wordpress/
 
 SYMBOLIC=
-LOG_DIRECTORY=
-LOG_UNINSTALL="/usr/local/bin/log-uninstall"
+TARGET_DIRECTORY=
+UNINSTALL_SCRIPT="/usr/local/bin/log-uninstall"
 
 if [ "${1}" == "" ] ; then
-  echo "usage: install [-s] log_directory"
+  echo "usage: install [-s] ( log_directory | wordpress_directory )"
   exit 1
 fi
 
@@ -19,34 +19,48 @@ while [ "${1}" != "" ] ; do
       echo "install: installing by symbolic link"
       ;;
     *)
-      LOG_DIRECTORY="${1}"
+      TARGET_DIRECTORY="${1}"
       ;;
   esac
 done
 
-if [ "${LOG_DIRECTORY}" == "" ] ; then
-  echo "install: log directory must be specified"
+if [ "${TARGET_DIRECTORY}" == "" ] ; then
+  echo "install: log directory or WordPress directory must be specified"
   exit 1
+fi
+
+# Determine installation type
+if [ -f "${TARGET_DIRECTORY}/wp-config.php" ] ; then
+  SOURCE_DIRECTORY=${WORDPRESS_SOURCE_DIRECTORY}
 else
-  if [ ! -d "${LOG_DIRECTORY}" ] ; then
-    mkdir -p "${LOG_DIRECTORY}"
-    chmod 777 "${LOG_DIRECTORY}"
+  SOURCE_DIRECTORY=${LOG_SOURCE_DIRECTORY}
+  DATA_DIRECTORY="${TARGET_DIRECTORY}"
+  TARGET_DIRECTORY="/"
+  if [ ! -f "${DATA_DIRECTORY}" ] ; then
+    if [ ! -d "${DATA_DIRECTORY}" ] ; then
+      mkdir -p "${DATA_DIRECTORY}"
+      chmod 777 "${DATA_DIRECTORY}"
+    fi
+  else
+    echo "install: log directory cannot be created because a file with the specified name already exists"
+    exit 1
   fi
 fi
 
-rm "${LOG_UNINSTALL}"
-touch "${LOG_UNINSTALL}"
+rm "${UNINSTALL_SCRIPT}"
+echo "#!/bin/bash" > "${UNINSTALL_SCRIPT}"
+chmod 755 "${UNINSTALL_SCRIPT}"
     
-if [ -d "${LOG_FOLDER}" ] ; then
-  cd "${LOG_FOLDER}"
+if [ -d "${SOURCE_DIRECTORY}" ] ; then
+  cd "${SOURCE_DIRECTORY}"
   for INSTALL_DIR_PATTERN in * ; do
-    INSTALL_DIR="/${INSTALL_DIR_PATTERN//\.//}"
+    INSTALL_DIR="${TARGET_DIRECTORY}${INSTALL_DIR_PATTERN//\.//}"
     pushd "${INSTALL_DIR_PATTERN}" > /dev/null
     for SCRIPT_NAME in * ; do
       SCRIPT_PATHNAME=$( realpath ${SCRIPT_NAME} )
       pushd "${INSTALL_DIR}" > /dev/null
       rm -f ${SCRIPT_NAME}
-      echo "rm \"${INSTALL_DIR}${SCRIPT_NAME}\"" >> "${LOG_UNINSTALL}"
+      echo "rm \"${INSTALL_DIR}${SCRIPT_NAME}\"" >> "${UNINSTALL_SCRIPT}"
       if [ "${SYMBOLIC}" == "yes" ] ; then
         ln -s "${SCRIPT_PATHNAME}" .
       else
@@ -58,3 +72,6 @@ if [ -d "${LOG_FOLDER}" ] ; then
     popd > /dev/null
   done
 fi
+
+echo "rm \"${UNINSTALL_SCRIPT}\"" >> "${UNINSTALL_SCRIPT}"
+
